# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Hotel\Views\CreateAcc.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateAcc(object):
    def setupUi(self, CreateAcc):
        CreateAcc.setObjectName("CreateAcc")
        CreateAcc.setEnabled(True)
        CreateAcc.resize(480, 640)
        self.label = QtWidgets.QLabel(CreateAcc)
        self.label.setGeometry(QtCore.QRect(130, 110, 221, 61))
        self.label.setStyleSheet("font-size:28pt;")
        self.label.setObjectName("label")
        self.username = QtWidgets.QLineEdit(CreateAcc)
        self.username.setGeometry(QtCore.QRect(120, 220, 240, 31))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(CreateAcc)
        self.password.setGeometry(QtCore.QRect(120, 270, 240, 31))
        self.password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password.setObjectName("password")
        self.signupbutton = QtWidgets.QPushButton(CreateAcc)
        self.signupbutton.setGeometry(QtCore.QRect(180, 380, 120, 31))
        self.signupbutton.setObjectName("signupbutton")
        self.password_2 = QtWidgets.QLineEdit(CreateAcc)
        self.password_2.setGeometry(QtCore.QRect(120, 320, 240, 31))
        self.password_2.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password_2.setObjectName("password_2")

        self.retranslateUi(CreateAcc)
        QtCore.QMetaObject.connectSlotsByName(CreateAcc)

    def retranslateUi(self, CreateAcc):
        _translate = QtCore.QCoreApplication.translate
        CreateAcc.setWindowTitle(_translate("CreateAcc", "CreateAcc"))
        self.label.setText(_translate("CreateAcc", "Регистрация"))
        self.username.setPlaceholderText(_translate("CreateAcc", "Логин"))
        self.password.setPlaceholderText(_translate("CreateAcc", "Пароль"))
        self.signupbutton.setText(_translate("CreateAcc", "Зарегестрироваться"))
        self.password_2.setPlaceholderText(_translate("CreateAcc", "Подтверждение пароля"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateAcc = QtWidgets.QDialog()
    ui = Ui_CreateAcc()
    ui.setupUi(CreateAcc)
    CreateAcc.show()
    sys.exit(app.exec_())
