# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Hotel\Views\Categories.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Categories(object):
    def setupUi(self, Categories):
        Categories.setObjectName("Categories")
        Categories.setEnabled(True)
        Categories.resize(881, 639)
        Categories.setMouseTracking(True)
        Categories.setTabletTracking(True)
        self.centralwidget = QtWidgets.QWidget(Categories)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 881, 461))
        self.tableWidget.setMaximumSize(QtCore.QSize(881, 16777215))
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setGeometry(QtCore.QRect(20, 480, 101, 23))
        self.update_button.setObjectName("update_button")
        self.alter_button = QtWidgets.QPushButton(self.centralwidget)
        self.alter_button.setGeometry(QtCore.QRect(20, 570, 101, 23))
        self.alter_button.setObjectName("alter_button")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(20, 510, 101, 23))
        self.add_button.setObjectName("add_button")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setGeometry(QtCore.QRect(20, 540, 101, 23))
        self.delete_button.setObjectName("delete_button")
        self.adding_type = QtWidgets.QLineEdit(self.centralwidget)
        self.adding_type.setGeometry(QtCore.QRect(130, 510, 113, 20))
        self.adding_type.setText("")
        self.adding_type.setMaxLength(25)
        self.adding_type.setObjectName("adding_type")
        self.adding_desc = QtWidgets.QLineEdit(self.centralwidget)
        self.adding_desc.setGeometry(QtCore.QRect(250, 510, 113, 20))
        self.adding_desc.setMaxLength(255)
        self.adding_desc.setObjectName("adding_desc")
        self.id_category = QtWidgets.QLineEdit(self.centralwidget)
        self.id_category.setGeometry(QtCore.QRect(130, 540, 113, 20))
        self.id_category.setObjectName("id_category")
        self.delete_type = QtWidgets.QLineEdit(self.centralwidget)
        self.delete_type.setGeometry(QtCore.QRect(250, 540, 113, 20))
        self.delete_type.setText("")
        self.delete_type.setMaxLength(25)
        self.delete_type.setObjectName("delete_type")
        #Categories.setCentralWidget(self.centralwidget)

        self.retranslateUi(Categories)
        QtCore.QMetaObject.connectSlotsByName(Categories)

    def retranslateUi(self, Categories):
        _translate = QtCore.QCoreApplication.translate
        Categories.setWindowTitle(_translate("Categories", "Справочник категорий"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Categories", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Categories", "Тип"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Categories", "Описание"))
        self.update_button.setText(_translate("Categories", "Обновить"))
        self.alter_button.setText(_translate("Categories", "Редактировать"))
        self.add_button.setText(_translate("Categories", "Добавить"))
        self.delete_button.setText(_translate("Categories", "Удалить"))
        self.adding_type.setPlaceholderText(_translate("Categories", "Тип"))
        self.adding_desc.setPlaceholderText(_translate("Categories", "Описание"))
        self.id_category.setPlaceholderText(_translate("Categories", "id"))
        self.delete_type.setPlaceholderText(_translate("Categories", "Тип"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Categories = QtWidgets.QMainWindow()
    ui = Ui_Categories()
    ui.setupUi(Categories)
    Categories.show()
    sys.exit(app.exec_())
