# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Hotel\Views\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setEnabled(True)
        Login.resize(480, 640)
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(200, 120, 120, 61))
        self.label.setStyleSheet("font-size:28pt;")
        self.label.setObjectName("label")
        self.username = QtWidgets.QLineEdit(Login)
        self.username.setGeometry(QtCore.QRect(120, 220, 240, 31))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(Login)
        self.password.setGeometry(QtCore.QRect(120, 290, 240, 31))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.loginbutton = QtWidgets.QPushButton(Login)
        self.loginbutton.setGeometry(QtCore.QRect(180, 380, 120, 31))
        self.loginbutton.setObjectName("loginbutton")
        self.pushButton = QtWidgets.QPushButton(Login)
        self.pushButton.setGeometry(QtCore.QRect(180, 440, 121, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.label.setText(_translate("Login", "Вход"))
        self.username.setPlaceholderText(_translate("Login", "Логин"))
        self.password.setPlaceholderText(_translate("Login", "Пароль"))
        self.loginbutton.setText(_translate("Login", "Логин"))
        self.pushButton.setText(_translate("Login", "Войти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
