# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Hotel\Views\Positions.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Positions(object):
    def setupUi(self, Positions):
        Positions.setObjectName("Positions")
        Positions.setEnabled(True)
        Positions.resize(881, 639)
        Positions.setMouseTracking(True)
        Positions.setTabletTracking(True)
        self.centralwidget = QtWidgets.QWidget(Positions)
        self.centralwidget.setObjectName("centralwidget")
        self.positions_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.positions_tableWidget.setEnabled(True)
        self.positions_tableWidget.setGeometry(QtCore.QRect(0, 0, 881, 461))
        self.positions_tableWidget.setMaximumSize(QtCore.QSize(881, 16777215))
        self.positions_tableWidget.setMouseTracking(False)
        self.positions_tableWidget.setAutoFillBackground(True)
        self.positions_tableWidget.setObjectName("positions_tableWidget")
        self.positions_tableWidget.setColumnCount(3)
        self.positions_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.positions_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.positions_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        self.positions_tableWidget.setHorizontalHeaderItem(2, item)
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setGeometry(QtCore.QRect(20, 480, 101, 23))
        self.update_button.setObjectName("update_button")
        self.alter_button = QtWidgets.QPushButton(self.centralwidget)
        self.alter_button.setGeometry(QtCore.QRect(20, 570, 101, 23))
        self.alter_button.setObjectName("alter_button")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(20, 510, 101, 23))
        self.add_button.setObjectName("add_button")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setGeometry(QtCore.QRect(20, 540, 101, 23))
        self.delete_button.setObjectName("delete_button")
        self.position_name = QtWidgets.QLineEdit(self.centralwidget)
        self.position_name.setGeometry(QtCore.QRect(130, 510, 113, 20))
        self.position_name.setText("")
        self.position_name.setMaxLength(50)
        self.position_name.setObjectName("position_name")
        self.adding_desc = QtWidgets.QLineEdit(self.centralwidget)
        self.adding_desc.setGeometry(QtCore.QRect(250, 510, 113, 20))
        self.adding_desc.setMaxLength(255)
        self.adding_desc.setObjectName("adding_desc")
        self.id_position = QtWidgets.QLineEdit(self.centralwidget)
        self.id_position.setGeometry(QtCore.QRect(130, 540, 113, 20))
        self.id_position.setObjectName("id_position")
        self.delete_type = QtWidgets.QLineEdit(self.centralwidget)
        self.delete_type.setGeometry(QtCore.QRect(250, 540, 113, 20))
        self.delete_type.setText("")
        self.delete_type.setMaxLength(25)
        self.delete_type.setObjectName("delete_type")
        #Positions.setCentralWidget(self.centralwidget)

        self.retranslateUi(Positions)
        QtCore.QMetaObject.connectSlotsByName(Positions)

    def retranslateUi(self, Positions):
        _translate = QtCore.QCoreApplication.translate
        Positions.setWindowTitle(_translate("Positions", "Справочник позиций сотрудников"))
        item = self.positions_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Positions", "ID"))
        item = self.positions_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Positions", "Название"))
        item = self.positions_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Positions", "Описание"))
        self.update_button.setText(_translate("Positions", "Обновить"))
        self.alter_button.setText(_translate("Positions", "Редактировать"))
        self.add_button.setText(_translate("Positions", "Добавить"))
        self.delete_button.setText(_translate("Positions", "Удалить"))
        self.position_name.setPlaceholderText(_translate("Positions", "Название"))
        self.adding_desc.setPlaceholderText(_translate("Positions", "Описание"))
        self.id_position.setPlaceholderText(_translate("Positions", "id"))
        self.delete_type.setPlaceholderText(_translate("Positions", "Название"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Positions = QtWidgets.QMainWindow()
    ui = Ui_Positions()
    ui.setupUi(Positions)
    Positions.show()
    sys.exit(app.exec_())
