# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Hotel\Views\Properties.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Property(object):
    def setupUi(self, Property):
        Property.setObjectName("Property")
        Property.setEnabled(True)
        Property.resize(634, 307)
        Property.setMouseTracking(True)
        Property.setTabletTracking(True)
        self.widget = QtWidgets.QWidget(Property)
        self.widget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.widget.setObjectName("widget")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(0, 10, 261, 281))
        self.tableWidget.setMaximumSize(QtCore.QSize(881, 16777215))
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.alter_button = QtWidgets.QPushButton(self.widget)
        self.alter_button.setGeometry(QtCore.QRect(270, 180, 101, 23))
        self.alter_button.setObjectName("alter_button")
        self.add_button = QtWidgets.QPushButton(self.widget)
        self.add_button.setGeometry(QtCore.QRect(270, 60, 101, 23))
        self.add_button.setObjectName("add_button")
        self.delete_button = QtWidgets.QPushButton(self.widget)
        self.delete_button.setGeometry(QtCore.QRect(270, 120, 101, 23))
        self.delete_button.setObjectName("delete_button")
        self.adding_type = QtWidgets.QLineEdit(self.widget)
        self.adding_type.setGeometry(QtCore.QRect(380, 60, 113, 20))
        self.adding_type.setText("")
        self.adding_type.setMaxLength(50)
        self.adding_type.setObjectName("adding_type")
        self.id_property = QtWidgets.QLineEdit(self.widget)
        self.id_property.setGeometry(QtCore.QRect(380, 120, 113, 20))
        self.id_property.setObjectName("id_property")
        self.delete_type = QtWidgets.QLineEdit(self.widget)
        self.delete_type.setGeometry(QtCore.QRect(500, 120, 113, 20))
        self.delete_type.setText("")
        self.delete_type.setMaxLength(25)
        self.delete_type.setObjectName("delete_type")
        #Property.setCentralWidget(self.widget)

        self.retranslateUi(Property)
        QtCore.QMetaObject.connectSlotsByName(Property)

    def retranslateUi(self, Property):
        _translate = QtCore.QCoreApplication.translate
        Property.setWindowTitle(_translate("Property", "Справочник свойст номеров"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Property", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Property", "Название"))
        self.alter_button.setText(_translate("Property", "Редактировать"))
        self.add_button.setText(_translate("Property", "Добавить"))
        self.delete_button.setText(_translate("Property", "Удалить"))
        self.adding_type.setPlaceholderText(_translate("Property", "Название"))
        self.id_property.setPlaceholderText(_translate("Property", "id"))
        self.delete_type.setPlaceholderText(_translate("Property", "Название"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Property = QtWidgets.QMainWindow()
    ui = Ui_Property()
    ui.setupUi(Property)
    Property.show()
    sys.exit(app.exec_())
