# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Hotel\Views\Statuses.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Status(object):
    def setupUi(self, Status):
        Status.setObjectName("Status")
        Status.setEnabled(True)
        Status.resize(634, 307)
        Status.setMouseTracking(True)
        Status.setTabletTracking(True)
        self.widget = QtWidgets.QWidget(Status)
        self.widget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.widget.setObjectName("widget")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(0, 10, 261, 281))
        self.tableWidget.setMaximumSize(QtCore.QSize(881, 16777215))
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.alter_button = QtWidgets.QPushButton(self.widget)
        self.alter_button.setGeometry(QtCore.QRect(270, 180, 101, 23))
        self.alter_button.setObjectName("alter_button")
        self.add_button = QtWidgets.QPushButton(self.widget)
        self.add_button.setGeometry(QtCore.QRect(270, 60, 101, 23))
        self.add_button.setObjectName("add_button")
        self.delete_button = QtWidgets.QPushButton(self.widget)
        self.delete_button.setGeometry(QtCore.QRect(270, 120, 101, 23))
        self.delete_button.setObjectName("delete_button")
        self.adding_type = QtWidgets.QLineEdit(self.widget)
        self.adding_type.setGeometry(QtCore.QRect(380, 60, 113, 20))
        self.adding_type.setText("")
        self.adding_type.setMaxLength(50)
        self.adding_type.setObjectName("adding_type")
        self.id_category = QtWidgets.QLineEdit(self.widget)
        self.id_category.setGeometry(QtCore.QRect(380, 120, 113, 20))
        self.id_category.setObjectName("id_category")
        self.delete_type = QtWidgets.QLineEdit(self.widget)
        self.delete_type.setGeometry(QtCore.QRect(500, 120, 113, 20))
        self.delete_type.setText("")
        self.delete_type.setMaxLength(25)
        self.delete_type.setObjectName("delete_type")
        #Status.setCentralWidget(self.widget)

        self.retranslateUi(Status)
        QtCore.QMetaObject.connectSlotsByName(Status)

    def retranslateUi(self, Status):
        _translate = QtCore.QCoreApplication.translate
        Status.setWindowTitle(_translate("Status", "Справочник позиций сотрудников"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Status", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Status", "Название"))
        self.alter_button.setText(_translate("Status", "Редактировать"))
        self.add_button.setText(_translate("Status", "Добавить"))
        self.delete_button.setText(_translate("Status", "Удалить"))
        self.adding_type.setPlaceholderText(_translate("Status", "Название"))
        self.id_category.setPlaceholderText(_translate("Status", "id"))
        self.delete_type.setPlaceholderText(_translate("Status", "Название"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Status = QtWidgets.QMainWindow()
    ui = Ui_Status()
    ui.setupUi(Status)
    Status.show()
    sys.exit(app.exec_())
